apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: platform-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: platform-cluster-role
  apiGroup: rbac.authorization.k8s.io